# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persona.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersona.proto\"\x8f\x01\n\x07persona\x12\x12\n\nlocal_name\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x10\n\x08node_num\x18\x03 \x01(\x05\x12\x12\n\npublic_key\x18\x04 \x01(\x0c\x12\x13\n\x0bprivate_key\x18\x05 \x01(\x0c\x1a \n\tall_peers\x12\x13\n\x04peer\x18\x01 \x03(\x0b\x32\x05.Peer\"\'\n\x0bsecret_book\x12\x18\n\x06person\x18\x01 \x03(\x0b\x32\x08.persona\"C\n\x04Peer\x12\x12\n\nlocal_name\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x13\n\x0bprivate_key\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persona_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONA._serialized_start=18
  _PERSONA._serialized_end=161
  _PERSONA_ALL_PEERS._serialized_start=129
  _PERSONA_ALL_PEERS._serialized_end=161
  _SECRET_BOOK._serialized_start=163
  _SECRET_BOOK._serialized_end=202
  _PEER._serialized_start=204
  _PEER._serialized_end=271
# @@protoc_insertion_point(module_scope)
